packages:
  - ./frontend
catalog:
  '@serenity-kit/opaque': ^1.1.0
  oxfmt: ^0.45.0
  oxlint: ^1.60.0
  typescript: ^6.0.3
  vite: ^8.0.8

catalogMode: strict
cleanupUnusedCatalogs: true

dedupePeers: true

engineStrict: true
failIfNoMatch: true
